name: ariane_mobile
description: "Ariane Mobile Testing App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.7+8
  hooks_riverpod: ^2.5.1
  go_router: ^13.0.1
  loggy: ^2.0.3
  dio: ^5.5.0+1
  fpdart: ^1.1.0
  riverpod_annotation: ^2.3.5
  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.2
  flutter_hooks: ^0.20.5
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  flutter_onboarding_slider: ^1.0.11
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  hive: ^2.2.3
  riverpod_lint: ^2.3.10
  flutter_advanced_drawer: ^1.3.6
  flutter_svg: ^2.0.10+1
  flutter_easy_faq: ^1.0.1
  intl: ^0.19.0
  carousel_slider_plus: ^6.0.0
  oidc: ^0.7.0
  oidc_default_store: ^0.2.0+9
  oidc_core: ^0.7.0
  flutter_secure_storage: ^9.2.2
  bdaya_shared_value: ^3.1.3
  async: ^2.11.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  go_router_builder: ^2.7.0
  riverpod_generator: ^2.4.0
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: "assets/images/logo-no-background.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo-no-background.png
  color_dark: "#ffffff"
  image_dark: assets/images/logo-no-background.png
  android_12:
    image: assets/images/logo-no-background.png
    color: "#ffffff"
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true

  # fonts:
  #   - family: Plus Jakarta Sans
  #     fonts:
  #       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  #       - asset: assets/fonts/PlusJakartaSans-Bold.ttf
  #         weight: 700

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/